sections:
    - name: Moje Serwisy
      icon: svg/docker.svg
      links:
          - name: Homepage 80
            href: http://127.0.0.1/
            icon: svg/diagrams-net.svg
            health-check: http://192.168.31.253/live
search:
    placeholder: Search the web...
    name: Google
    url: https://www.google.com/search
fallbackIcon:
    name: svg/xwiki.svg
