sections:
 - name: "Filmy i seriale"
   icon: "films.jpg"
   links:
     - name: "Netflix (Filmy)"
       href: "https://www.netflix.com/"
       icon: "netflix.png"
     - name: "Youtube"
       href: "https://www.youtube.com/"
       icon: "youtube.png"

 - name: "Banki"
   icon: "bank.png"
   links:
     - name: "PKO"
       href: "https://www.pkobp.pl"
       icon: "bank.png"
     - name: "Millenium"
       href: "https://www.bankmillennium.pl"
       icon: "bank.png"

 - name: "Social Media"
   icon: "social.png"
   links:
     - name: "Facebook"
       href: "https://www.facebook.com"
       icon: "facebook.png"
     - name: "X (Twitter)"
       href: "https://www.twitter.com"
       icon: "social.png"

search:
 placeholder: "Search the web..."
 name: "Google"
 url: "https://www.google.com/search"

fallbackIcon:
  name: search.jpg
