sections:
  - name: Apple
    icon: apple.svg
    links:
      - name: Apple TV+
        href: 'https://www.apple.com/apple-tv-plus/'
        icon: appletv.svg
      - name: Apple Music
        href: 'https://www.apple.com/apple-music/'
        icon: applemusic.svg
  - name: Social Media
    icon: social.png
    links:
      - name: Facebook
        href: 'https://www.facebook.com'
        icon: facebook.svg
search:
  placeholder: Search the web...
  name: Google
  url: 'https://www.google.com/search'
fallbackIcon:
  name: deutschebank.svg
