sections:
    - name: Section 1
      icon: apple.svg
      links:
          - name: ApplePay
            href: https://www.apple.com/pl/apple-pay/
            icon: applepay.svg
    - name: Section 2
      icon: social.png
      links:
          - name: Google
            href: https://www.google.com
            icon: facebook.svg
search:
    placeholder: Search the web...
    name: Google
    url: https://www.google.com/search
fallbackIcon:
    name: no-icon.svg
