name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Pobranie kodu źródłowego
    - name: Checkout code
      uses: actions/checkout@v3

    # Instalacja Node.js i zależności
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '13'

    - name: Install dependencies
      run: npm install

    # Testowanie aplikacji
    - name: Run tests
      run: npm test

    # Budowanie obrazu Dockera
    - name: Build Docker image
      run: docker build -t my-app .

    # Logowanie do Docker Hub (opcjonalne, jeśli korzystasz z Docker Hub)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Publikowanie obrazu Dockera
    - name: Push Docker image
      run: docker push my-app:latest
