name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this secret in your repo settings
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set this secret in your repo settings

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app_code  # Path to your Dockerfile and application
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/chmurowe:latest
          ${{ secrets.DOCKER_USERNAME }}/chmurowe:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

    - name: Verify Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/chmurowe:latest
        docker images
